//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.11 at 04:49:31 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types}ResultStatusFlag"/>
 *         &lt;element name="CardId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PostingGUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PaymentAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="PaymentInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CouponFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LoyaltyMenuItemList" type="{http://www.hrs.ru/clubng/ws/common/types}LoyaltyMenuItemList"/>
 *         &lt;element name="GiftMenuItems" type="{http://www.hrs.ru/clubng/ws/common/types}MenuItemList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "cardId",
    "postingGUID",
    "paymentAmount",
    "paymentInfo",
    "couponFlag",
    "loyaltyMenuItemList",
    "giftMenuItems"
})
@XmlRootElement(name = "AcquireLoyaltyResponse")
public class AcquireLoyaltyResponse {

    @XmlElement(name = "Status", required = true)
    protected ResultStatusFlag status;
    @XmlElement(name = "CardId", required = true)
    protected String cardId;
    @XmlElement(name = "PostingGUID", required = true)
    protected String postingGUID;
    @XmlElement(name = "PaymentAmount")
    protected double paymentAmount;
    @XmlElement(name = "PaymentInfo", required = true)
    protected String paymentInfo;
    @XmlElement(name = "CouponFlag", required = true)
    protected String couponFlag;
    @XmlElement(name = "LoyaltyMenuItemList", required = true)
    protected LoyaltyMenuItemList loyaltyMenuItemList;
    @XmlElement(name = "GiftMenuItems")
    protected MenuItemList giftMenuItems;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ResultStatusFlag }
     *     
     */
    public ResultStatusFlag getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultStatusFlag }
     *     
     */
    public void setStatus(ResultStatusFlag value) {
        this.status = value;
    }

    /**
     * Gets the value of the cardId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * Sets the value of the cardId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardId(String value) {
        this.cardId = value;
    }

    /**
     * Gets the value of the postingGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostingGUID() {
        return postingGUID;
    }

    /**
     * Sets the value of the postingGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostingGUID(String value) {
        this.postingGUID = value;
    }

    /**
     * Gets the value of the paymentAmount property.
     * 
     */
    public double getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * Sets the value of the paymentAmount property.
     * 
     */
    public void setPaymentAmount(double value) {
        this.paymentAmount = value;
    }

    /**
     * Gets the value of the paymentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentInfo() {
        return paymentInfo;
    }

    /**
     * Sets the value of the paymentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentInfo(String value) {
        this.paymentInfo = value;
    }

    /**
     * Gets the value of the couponFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouponFlag() {
        return couponFlag;
    }

    /**
     * Sets the value of the couponFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouponFlag(String value) {
        this.couponFlag = value;
    }

    /**
     * Gets the value of the loyaltyMenuItemList property.
     * 
     * @return
     *     possible object is
     *     {@link LoyaltyMenuItemList }
     *     
     */
    public LoyaltyMenuItemList getLoyaltyMenuItemList() {
        return loyaltyMenuItemList;
    }

    /**
     * Sets the value of the loyaltyMenuItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoyaltyMenuItemList }
     *     
     */
    public void setLoyaltyMenuItemList(LoyaltyMenuItemList value) {
        this.loyaltyMenuItemList = value;
    }

    /**
     * Gets the value of the giftMenuItems property.
     * 
     * @return
     *     possible object is
     *     {@link MenuItemList }
     *     
     */
    public MenuItemList getGiftMenuItems() {
        return giftMenuItems;
    }

    /**
     * Sets the value of the giftMenuItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link MenuItemList }
     *     
     */
    public void setGiftMenuItems(MenuItemList value) {
        this.giftMenuItems = value;
    }

}
