//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 01:38:32 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RegisterId" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types}UniqueID"/>
 *         &lt;element name="postingGUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VoidFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DocFacsimile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MenuItemList" type="{http://www.hrs.ru/clubng/ws/common/types}MenuItemList" minOccurs="0"/>
 *         &lt;element name="PaymentList" type="{http://www.hrs.ru/clubng/ws/common/types}PaymentListType" minOccurs="0"/>
 *         &lt;element name="TaxList" type="{http://www.hrs.ru/clubng/ws/common/types}TaxListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "registerId",
    "postingGUID",
    "voidFlag",
    "docFacsimile",
    "menuItemList",
    "paymentList",
    "taxList"
})
@XmlRootElement(name = "DocConfirmRequest")
public class DocConfirmRequest {

    @XmlElement(name = "RegisterId", required = true)
    protected UniqueID registerId;
    @XmlElement(required = true)
    protected String postingGUID;
    @XmlElement(name = "VoidFlag", required = true)
    protected String voidFlag;
    @XmlElement(name = "DocFacsimile")
    protected String docFacsimile;
    @XmlElement(name = "MenuItemList")
    protected MenuItemList menuItemList;
    @XmlElement(name = "PaymentList")
    protected PaymentListType paymentList;
    @XmlElement(name = "TaxList")
    protected TaxListType taxList;

    /**
     * Gets the value of the registerId property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueID }
     *     
     */
    public UniqueID getRegisterId() {
        return registerId;
    }

    /**
     * Sets the value of the registerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueID }
     *     
     */
    public void setRegisterId(UniqueID value) {
        this.registerId = value;
    }

    /**
     * Gets the value of the postingGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostingGUID() {
        return postingGUID;
    }

    /**
     * Sets the value of the postingGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostingGUID(String value) {
        this.postingGUID = value;
    }

    /**
     * Gets the value of the voidFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoidFlag() {
        return voidFlag;
    }

    /**
     * Sets the value of the voidFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoidFlag(String value) {
        this.voidFlag = value;
    }

    /**
     * Gets the value of the docFacsimile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocFacsimile() {
        return docFacsimile;
    }

    /**
     * Sets the value of the docFacsimile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocFacsimile(String value) {
        this.docFacsimile = value;
    }

    /**
     * Gets the value of the menuItemList property.
     * 
     * @return
     *     possible object is
     *     {@link MenuItemList }
     *     
     */
    public MenuItemList getMenuItemList() {
        return menuItemList;
    }

    /**
     * Sets the value of the menuItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MenuItemList }
     *     
     */
    public void setMenuItemList(MenuItemList value) {
        this.menuItemList = value;
    }

    /**
     * Gets the value of the paymentList property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentListType }
     *     
     */
    public PaymentListType getPaymentList() {
        return paymentList;
    }

    /**
     * Sets the value of the paymentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentListType }
     *     
     */
    public void setPaymentList(PaymentListType value) {
        this.paymentList = value;
    }

    /**
     * Gets the value of the taxList property.
     * 
     * @return
     *     possible object is
     *     {@link TaxListType }
     *     
     */
    public TaxListType getTaxList() {
        return taxList;
    }

    /**
     * Sets the value of the taxList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxListType }
     *     
     */
    public void setTaxList(TaxListType value) {
        this.taxList = value;
    }

}
