//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 01:38:32 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProfileID" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types}UniqueID"/>
 *         &lt;element name="CardType" type="{http://www.hrs.ru/clubng/ws/common/types}CardType"/>
 *         &lt;element name="CardStatus" type="{http://www.hrs.ru/clubng/ws/common/types}CardStatus"/>
 *         &lt;element name="PersonName" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types}PersonName" minOccurs="0"/>
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Phone" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types}Phone" minOccurs="0"/>
 *         &lt;element name="TextData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HTMLData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Accounts" type="{http://www.hrs.ru/clubng/ws/common/types}AccountInfoListType"/>
 *         &lt;element name="Vouchers" type="{http://www.hrs.ru/clubng/ws/common/types}VoucherInfoListType"/>
 *         &lt;element name="Coupons" type="{http://www.hrs.ru/clubng/ws/common/types}CouponInfoListType"/>
 *         &lt;element name="Cards" type="{http://www.hrs.ru/clubng/ws/common/types}CardInfoListType"/>
 *         &lt;element name="canOpenCheck" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="TicketClassLimits" type="{http://www.hrs.ru/clubng/ws/common/types}TicketClassLimits" minOccurs="0"/>
 *         &lt;element name="TicketNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TicketCharges" type="{http://www.hrs.ru/clubng/ws/common/types}TicketChargesListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "profileID",
    "cardType",
    "cardStatus",
    "personName",
    "birthDate",
    "phone",
    "textData",
    "htmlData",
    "accounts",
    "vouchers",
    "coupons",
    "cards",
    "canOpenCheck",
    "ticketClassLimits",
    "ticketNumber",
    "ticketCharges"
})
@XmlRootElement(name = "FetchProfileResponse")
public class FetchProfileResponse {

    @XmlElement(name = "ProfileID", required = true)
    protected UniqueID profileID;
    @XmlElement(name = "CardType", required = true)
    protected CardType cardType;
    @XmlElement(name = "CardStatus", required = true)
    protected CardStatus cardStatus;
    @XmlElement(name = "PersonName")
    protected PersonName personName;
    @XmlElement(name = "BirthDate")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(name = "Phone")
    protected Phone phone;
    @XmlElement(name = "TextData")
    protected String textData;
    @XmlElement(name = "HTMLData")
    protected String htmlData;
    @XmlElement(name = "Accounts", required = true)
    protected AccountInfoListType accounts;
    @XmlElement(name = "Vouchers", required = true)
    protected VoucherInfoListType vouchers;
    @XmlElement(name = "Coupons", required = true)
    protected CouponInfoListType coupons;
    @XmlElement(name = "Cards", required = true)
    protected CardInfoListType cards;
    protected boolean canOpenCheck;
    @XmlElement(name = "TicketClassLimits")
    protected TicketClassLimits ticketClassLimits;
    @XmlElement(name = "TicketNumber")
    protected String ticketNumber;
    @XmlElement(name = "TicketCharges")
    protected TicketChargesListType ticketCharges;

    /**
     * Gets the value of the profileID property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueID }
     *     
     */
    public UniqueID getProfileID() {
        return profileID;
    }

    /**
     * Sets the value of the profileID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueID }
     *     
     */
    public void setProfileID(UniqueID value) {
        this.profileID = value;
    }

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link CardType }
     *     
     */
    public CardType getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardType }
     *     
     */
    public void setCardType(CardType value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the cardStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CardStatus }
     *     
     */
    public CardStatus getCardStatus() {
        return cardStatus;
    }

    /**
     * Sets the value of the cardStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardStatus }
     *     
     */
    public void setCardStatus(CardStatus value) {
        this.cardStatus = value;
    }

    /**
     * Gets the value of the personName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getPersonName() {
        return personName;
    }

    /**
     * Sets the value of the personName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setPersonName(PersonName value) {
        this.personName = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link Phone }
     *     
     */
    public Phone getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Phone }
     *     
     */
    public void setPhone(Phone value) {
        this.phone = value;
    }

    /**
     * Gets the value of the textData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextData() {
        return textData;
    }

    /**
     * Sets the value of the textData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextData(String value) {
        this.textData = value;
    }

    /**
     * Gets the value of the htmlData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHTMLData() {
        return htmlData;
    }

    /**
     * Sets the value of the htmlData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHTMLData(String value) {
        this.htmlData = value;
    }

    /**
     * Gets the value of the accounts property.
     * 
     * @return
     *     possible object is
     *     {@link AccountInfoListType }
     *     
     */
    public AccountInfoListType getAccounts() {
        return accounts;
    }

    /**
     * Sets the value of the accounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountInfoListType }
     *     
     */
    public void setAccounts(AccountInfoListType value) {
        this.accounts = value;
    }

    /**
     * Gets the value of the vouchers property.
     * 
     * @return
     *     possible object is
     *     {@link VoucherInfoListType }
     *     
     */
    public VoucherInfoListType getVouchers() {
        return vouchers;
    }

    /**
     * Sets the value of the vouchers property.
     * 
     * @param value
     *     allowed object is
     *     {@link VoucherInfoListType }
     *     
     */
    public void setVouchers(VoucherInfoListType value) {
        this.vouchers = value;
    }

    /**
     * Gets the value of the coupons property.
     * 
     * @return
     *     possible object is
     *     {@link CouponInfoListType }
     *     
     */
    public CouponInfoListType getCoupons() {
        return coupons;
    }

    /**
     * Sets the value of the coupons property.
     * 
     * @param value
     *     allowed object is
     *     {@link CouponInfoListType }
     *     
     */
    public void setCoupons(CouponInfoListType value) {
        this.coupons = value;
    }

    /**
     * Gets the value of the cards property.
     * 
     * @return
     *     possible object is
     *     {@link CardInfoListType }
     *     
     */
    public CardInfoListType getCards() {
        return cards;
    }

    /**
     * Sets the value of the cards property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardInfoListType }
     *     
     */
    public void setCards(CardInfoListType value) {
        this.cards = value;
    }

    /**
     * Gets the value of the canOpenCheck property.
     * 
     */
    public boolean isCanOpenCheck() {
        return canOpenCheck;
    }

    /**
     * Sets the value of the canOpenCheck property.
     * 
     */
    public void setCanOpenCheck(boolean value) {
        this.canOpenCheck = value;
    }

    /**
     * Gets the value of the ticketClassLimits property.
     * 
     * @return
     *     possible object is
     *     {@link TicketClassLimits }
     *     
     */
    public TicketClassLimits getTicketClassLimits() {
        return ticketClassLimits;
    }

    /**
     * Sets the value of the ticketClassLimits property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketClassLimits }
     *     
     */
    public void setTicketClassLimits(TicketClassLimits value) {
        this.ticketClassLimits = value;
    }

    /**
     * Gets the value of the ticketNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicketNumber() {
        return ticketNumber;
    }

    /**
     * Sets the value of the ticketNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicketNumber(String value) {
        this.ticketNumber = value;
    }

    /**
     * Gets the value of the ticketCharges property.
     * 
     * @return
     *     possible object is
     *     {@link TicketChargesListType }
     *     
     */
    public TicketChargesListType getTicketCharges() {
        return ticketCharges;
    }

    /**
     * Sets the value of the ticketCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link TicketChargesListType }
     *     
     */
    public void setTicketCharges(TicketChargesListType value) {
        this.ticketCharges = value;
    }

}
