//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 01:38:32 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MenuItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MenuItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qty" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="extPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="discount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="MajorGroup" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SubGroup" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AddonTax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="PostingDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="Tickets" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MenuItem", namespace = "http://www.hrs.ru/clubng/ws/common/types", propOrder = {
    "id",
    "name",
    "qty",
    "price",
    "extPrice",
    "discount",
    "majorGroup",
    "subGroup",
    "addonTax",
    "postingDate",
    "tickets",
    "reference"
})
public class MenuItem {

    @XmlElement(namespace = "http://www.hrs.ru/clubng/ws/common/types", required = true)
    protected String id;
    @XmlElement(namespace = "http://www.hrs.ru/clubng/ws/common/types", required = true)
    protected String name;
    @XmlElement(namespace = "http://www.hrs.ru/clubng/ws/common/types")
    protected int qty;
    @XmlElement(namespace = "http://www.hrs.ru/clubng/ws/common/types")
    protected double price;
    @XmlElement(namespace = "http://www.hrs.ru/clubng/ws/common/types")
    protected double extPrice;
    @XmlElement(namespace = "http://www.hrs.ru/clubng/ws/common/types")
    protected double discount;
    @XmlElement(name = "MajorGroup", namespace = "http://www.hrs.ru/clubng/ws/common/types")
    protected int majorGroup;
    @XmlElement(name = "SubGroup", namespace = "http://www.hrs.ru/clubng/ws/common/types")
    protected int subGroup;
    @XmlElement(name = "AddonTax", namespace = "http://www.hrs.ru/clubng/ws/common/types")
    protected double addonTax;
    @XmlElement(name = "PostingDate", namespace = "http://www.hrs.ru/clubng/ws/common/types")
    protected XMLGregorianCalendar postingDate;
    @XmlElement(name = "Tickets", namespace = "http://www.hrs.ru/clubng/ws/common/types")
    protected String tickets;
    @XmlElement(name = "Reference", namespace = "http://www.hrs.ru/clubng/ws/common/types")
    protected String reference;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     */
    public int getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     */
    public void setQty(int value) {
        this.qty = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(double value) {
        this.price = value;
    }

    /**
     * Gets the value of the extPrice property.
     * 
     */
    public double getExtPrice() {
        return extPrice;
    }

    /**
     * Sets the value of the extPrice property.
     * 
     */
    public void setExtPrice(double value) {
        this.extPrice = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     */
    public double getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     */
    public void setDiscount(double value) {
        this.discount = value;
    }

    /**
     * Gets the value of the majorGroup property.
     * 
     */
    public int getMajorGroup() {
        return majorGroup;
    }

    /**
     * Sets the value of the majorGroup property.
     * 
     */
    public void setMajorGroup(int value) {
        this.majorGroup = value;
    }

    /**
     * Gets the value of the subGroup property.
     * 
     */
    public int getSubGroup() {
        return subGroup;
    }

    /**
     * Sets the value of the subGroup property.
     * 
     */
    public void setSubGroup(int value) {
        this.subGroup = value;
    }

    /**
     * Gets the value of the addonTax property.
     * 
     */
    public double getAddonTax() {
        return addonTax;
    }

    /**
     * Sets the value of the addonTax property.
     * 
     */
    public void setAddonTax(double value) {
        this.addonTax = value;
    }

    /**
     * Gets the value of the postingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPostingDate() {
        return postingDate;
    }

    /**
     * Sets the value of the postingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPostingDate(XMLGregorianCalendar value) {
        this.postingDate = value;
    }

    /**
     * Gets the value of the tickets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTickets() {
        return tickets;
    }

    /**
     * Sets the value of the tickets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTickets(String value) {
        this.tickets = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

}
