//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 01:38:32 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.hrs.lassd.club.ws.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Profile_QNAME = new QName("http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types", "Profile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.hrs.lassd.club.ws.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TicketChargesEntry }
     * 
     */
    public TicketChargesEntry createTicketChargesEntry() {
        return new TicketChargesEntry();
    }

    /**
     * Create an instance of {@link DepositItem }
     * 
     */
    public DepositItem createDepositItem() {
        return new DepositItem();
    }

    /**
     * Create an instance of {@link QuickCheckInRequest }
     * 
     */
    public QuickCheckInRequest createQuickCheckInRequest() {
        return new QuickCheckInRequest();
    }

    /**
     * Create an instance of {@link CardInfoListType }
     * 
     */
    public CardInfoListType createCardInfoListType() {
        return new CardInfoListType();
    }

    /**
     * Create an instance of {@link NegotiatedRate }
     * 
     */
    public NegotiatedRate createNegotiatedRate() {
        return new NegotiatedRate();
    }

    /**
     * Create an instance of {@link PaymentListType }
     * 
     */
    public PaymentListType createPaymentListType() {
        return new PaymentListType();
    }

    /**
     * Create an instance of {@link DataItemListType }
     * 
     */
    public DataItemListType createDataItemListType() {
        return new DataItemListType();
    }

    /**
     * Create an instance of {@link DescriptiveText }
     * 
     */
    public DescriptiveText createDescriptiveText() {
        return new DescriptiveText();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link UpdateProfile2Response }
     * 
     */
    public UpdateProfile2Response createUpdateProfile2Response() {
        return new UpdateProfile2Response();
    }

    /**
     * Create an instance of {@link UniqueIDList }
     * 
     */
    public UniqueIDList createUniqueIDList() {
        return new UniqueIDList();
    }

    /**
     * Create an instance of {@link GovernmentIDList }
     * 
     */
    public GovernmentIDList createGovernmentIDList() {
        return new GovernmentIDList();
    }

    /**
     * Create an instance of {@link VoucherInfo }
     * 
     */
    public VoucherInfo createVoucherInfo() {
        return new VoucherInfo();
    }

    /**
     * Create an instance of {@link NamePhoneList }
     * 
     */
    public NamePhoneList createNamePhoneList() {
        return new NamePhoneList();
    }

    /**
     * Create an instance of {@link DocConfirmRequest }
     * 
     */
    public DocConfirmRequest createDocConfirmRequest() {
        return new DocConfirmRequest();
    }

    /**
     * Create an instance of {@link LookupResponse }
     * 
     */
    public LookupResponse createLookupResponse() {
        return new LookupResponse();
    }

    /**
     * Create an instance of {@link VoucherRequest }
     * 
     */
    public VoucherRequest createVoucherRequest() {
        return new VoucherRequest();
    }

    /**
     * Create an instance of {@link UserDefinedValueList }
     * 
     */
    public UserDefinedValueList createUserDefinedValueList() {
        return new UserDefinedValueList();
    }

    /**
     * Create an instance of {@link SourceList }
     * 
     */
    public SourceList createSourceList() {
        return new SourceList();
    }

    /**
     * Create an instance of {@link ClientImportRequest }
     * 
     */
    public ClientImportRequest createClientImportRequest() {
        return new ClientImportRequest();
    }

    /**
     * Create an instance of {@link AccountInfoListType }
     * 
     */
    public AccountInfoListType createAccountInfoListType() {
        return new AccountInfoListType();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link TicketClassLimit }
     * 
     */
    public TicketClassLimit createTicketClassLimit() {
        return new TicketClassLimit();
    }

    /**
     * Create an instance of {@link RedeemItemVoucherRequest }
     * 
     */
    public RedeemItemVoucherRequest createRedeemItemVoucherRequest() {
        return new RedeemItemVoucherRequest();
    }

    /**
     * Create an instance of {@link CommentList }
     * 
     */
    public CommentList createCommentList() {
        return new CommentList();
    }

    /**
     * Create an instance of {@link LoyaltyMenuItemList }
     * 
     */
    public LoyaltyMenuItemList createLoyaltyMenuItemList() {
        return new LoyaltyMenuItemList();
    }

    /**
     * Create an instance of {@link DataItem }
     * 
     */
    public DataItem createDataItem() {
        return new DataItem();
    }

    /**
     * Create an instance of {@link PreferenceList }
     * 
     */
    public PreferenceList createPreferenceList() {
        return new PreferenceList();
    }

    /**
     * Create an instance of {@link RegistrationResponse }
     * 
     */
    public RegistrationResponse createRegistrationResponse() {
        return new RegistrationResponse();
    }

    /**
     * Create an instance of {@link Preference }
     * 
     */
    public Preference createPreference() {
        return new Preference();
    }

    /**
     * Create an instance of {@link ProfileLookupList }
     * 
     */
    public ProfileLookupList createProfileLookupList() {
        return new ProfileLookupList();
    }

    /**
     * Create an instance of {@link NegotiatedRateList }
     * 
     */
    public NegotiatedRateList createNegotiatedRateList() {
        return new NegotiatedRateList();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link TicketChargesListType }
     * 
     */
    public TicketChargesListType createTicketChargesListType() {
        return new TicketChargesListType();
    }

    /**
     * Create an instance of {@link LockerResponse }
     * 
     */
    public LockerResponse createLockerResponse() {
        return new LockerResponse();
    }

    /**
     * Create an instance of {@link Subscription }
     * 
     */
    public Subscription createSubscription() {
        return new Subscription();
    }

    /**
     * Create an instance of {@link TicketClassLimits }
     * 
     */
    public TicketClassLimits createTicketClassLimits() {
        return new TicketClassLimits();
    }

    /**
     * Create an instance of {@link DepositItemList }
     * 
     */
    public DepositItemList createDepositItemList() {
        return new DepositItemList();
    }

    /**
     * Create an instance of {@link UpdateProfileRequest }
     * 
     */
    public UpdateProfileRequest createUpdateProfileRequest() {
        return new UpdateProfileRequest();
    }

    /**
     * Create an instance of {@link PostPaymentRequest.PaymentRestrictions }
     * 
     */
    public PostPaymentRequest.PaymentRestrictions createPostPaymentRequestPaymentRestrictions() {
        return new PostPaymentRequest.PaymentRestrictions();
    }

    /**
     * Create an instance of {@link NameAddressList }
     * 
     */
    public NameAddressList createNameAddressList() {
        return new NameAddressList();
    }

    /**
     * Create an instance of {@link DepositPackageResponse }
     * 
     */
    public DepositPackageResponse createDepositPackageResponse() {
        return new DepositPackageResponse();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link QuickCheckInResponse }
     * 
     */
    public QuickCheckInResponse createQuickCheckInResponse() {
        return new QuickCheckInResponse();
    }

    /**
     * Create an instance of {@link QuickCheckOutResponse }
     * 
     */
    public QuickCheckOutResponse createQuickCheckOutResponse() {
        return new QuickCheckOutResponse();
    }

    /**
     * Create an instance of {@link GovernmentID }
     * 
     */
    public GovernmentID createGovernmentID() {
        return new GovernmentID();
    }

    /**
     * Create an instance of {@link ProfileLookupResponse }
     * 
     */
    public ProfileLookupResponse createProfileLookupResponse() {
        return new ProfileLookupResponse();
    }

    /**
     * Create an instance of {@link ResultStatus }
     * 
     */
    public ResultStatus createResultStatus() {
        return new ResultStatus();
    }

    /**
     * Create an instance of {@link Phone.PhoneData }
     * 
     */
    public Phone.PhoneData createPhonePhoneData() {
        return new Phone.PhoneData();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link UpdateProfileResponse }
     * 
     */
    public UpdateProfileResponse createUpdateProfileResponse() {
        return new UpdateProfileResponse();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link MergeResponse }
     * 
     */
    public MergeResponse createMergeResponse() {
        return new MergeResponse();
    }

    /**
     * Create an instance of {@link ProfileList }
     * 
     */
    public ProfileList createProfileList() {
        return new ProfileList();
    }

    /**
     * Create an instance of {@link MenuItem }
     * 
     */
    public MenuItem createMenuItem() {
        return new MenuItem();
    }

    /**
     * Create an instance of {@link BlackList }
     * 
     */
    public BlackList createBlackList() {
        return new BlackList();
    }

    /**
     * Create an instance of {@link PaymentListItem }
     * 
     */
    public PaymentListItem createPaymentListItem() {
        return new PaymentListItem();
    }

    /**
     * Create an instance of {@link CardInfo }
     * 
     */
    public CardInfo createCardInfo() {
        return new CardInfo();
    }

    /**
     * Create an instance of {@link AccountInfo }
     * 
     */
    public AccountInfo createAccountInfo() {
        return new AccountInfo();
    }

    /**
     * Create an instance of {@link DepositPackageRequest }
     * 
     */
    public DepositPackageRequest createDepositPackageRequest() {
        return new DepositPackageRequest();
    }

    /**
     * Create an instance of {@link AcquireLoyaltyRequest }
     * 
     */
    public AcquireLoyaltyRequest createAcquireLoyaltyRequest() {
        return new AcquireLoyaltyRequest();
    }

    /**
     * Create an instance of {@link PostPaymentResponse }
     * 
     */
    public PostPaymentResponse createPostPaymentResponse() {
        return new PostPaymentResponse();
    }

    /**
     * Create an instance of {@link RegistrationRequest }
     * 
     */
    public RegistrationRequest createRegistrationRequest() {
        return new RegistrationRequest();
    }

    /**
     * Create an instance of {@link NameAddress }
     * 
     */
    public NameAddress createNameAddress() {
        return new NameAddress();
    }

    /**
     * Create an instance of {@link NamePhone }
     * 
     */
    public NamePhone createNamePhone() {
        return new NamePhone();
    }

    /**
     * Create an instance of {@link AcquireLoyaltyResponse }
     * 
     */
    public AcquireLoyaltyResponse createAcquireLoyaltyResponse() {
        return new AcquireLoyaltyResponse();
    }

    /**
     * Create an instance of {@link AddKeyResponse }
     * 
     */
    public AddKeyResponse createAddKeyResponse() {
        return new AddKeyResponse();
    }

    /**
     * Create an instance of {@link ProfileLookup }
     * 
     */
    public ProfileLookup createProfileLookup() {
        return new ProfileLookup();
    }

    /**
     * Create an instance of {@link FetchProfileRequest }
     * 
     */
    public FetchProfileRequest createFetchProfileRequest() {
        return new FetchProfileRequest();
    }

    /**
     * Create an instance of {@link CardStatus }
     * 
     */
    public CardStatus createCardStatus() {
        return new CardStatus();
    }

    /**
     * Create an instance of {@link NewProfileResponse }
     * 
     */
    public NewProfileResponse createNewProfileResponse() {
        return new NewProfileResponse();
    }

    /**
     * Create an instance of {@link DocConfirmResponse }
     * 
     */
    public DocConfirmResponse createDocConfirmResponse() {
        return new DocConfirmResponse();
    }

    /**
     * Create an instance of {@link PrivacyList }
     * 
     */
    public PrivacyList createPrivacyList() {
        return new PrivacyList();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link DepositRequest }
     * 
     */
    public DepositRequest createDepositRequest() {
        return new DepositRequest();
    }

    /**
     * Create an instance of {@link MenuItemList }
     * 
     */
    public MenuItemList createMenuItemList() {
        return new MenuItemList();
    }

    /**
     * Create an instance of {@link SubscriptionRequest }
     * 
     */
    public SubscriptionRequest createSubscriptionRequest() {
        return new SubscriptionRequest();
    }

    /**
     * Create an instance of {@link NameCreditCardList }
     * 
     */
    public NameCreditCardList createNameCreditCardList() {
        return new NameCreditCardList();
    }

    /**
     * Create an instance of {@link UpdateProfile2Request }
     * 
     */
    public UpdateProfile2Request createUpdateProfile2Request() {
        return new UpdateProfile2Request();
    }

    /**
     * Create an instance of {@link CardType }
     * 
     */
    public CardType createCardType() {
        return new CardType();
    }

    /**
     * Create an instance of {@link RedeemItemVoucherResponse }
     * 
     */
    public RedeemItemVoucherResponse createRedeemItemVoucherResponse() {
        return new RedeemItemVoucherResponse();
    }

    /**
     * Create an instance of {@link Tax }
     * 
     */
    public Tax createTax() {
        return new Tax();
    }

    /**
     * Create an instance of {@link LoyaltyMenuItem }
     * 
     */
    public LoyaltyMenuItem createLoyaltyMenuItem() {
        return new LoyaltyMenuItem();
    }

    /**
     * Create an instance of {@link DepositResponse }
     * 
     */
    public DepositResponse createDepositResponse() {
        return new DepositResponse();
    }

    /**
     * Create an instance of {@link CouponInfoListType }
     * 
     */
    public CouponInfoListType createCouponInfoListType() {
        return new CouponInfoListType();
    }

    /**
     * Create an instance of {@link CouponInfo }
     * 
     */
    public CouponInfo createCouponInfo() {
        return new CouponInfo();
    }

    /**
     * Create an instance of {@link NameMembership }
     * 
     */
    public NameMembership createNameMembership() {
        return new NameMembership();
    }

    /**
     * Create an instance of {@link VoucherResponse }
     * 
     */
    public VoucherResponse createVoucherResponse() {
        return new VoucherResponse();
    }

    /**
     * Create an instance of {@link NewProfileRequest }
     * 
     */
    public NewProfileRequest createNewProfileRequest() {
        return new NewProfileRequest();
    }

    /**
     * Create an instance of {@link PrivacyOptionType }
     * 
     */
    public PrivacyOptionType createPrivacyOptionType() {
        return new PrivacyOptionType();
    }

    /**
     * Create an instance of {@link UserDefinedValue }
     * 
     */
    public UserDefinedValue createUserDefinedValue() {
        return new UserDefinedValue();
    }

    /**
     * Create an instance of {@link LookupRequest }
     * 
     */
    public LookupRequest createLookupRequest() {
        return new LookupRequest();
    }

    /**
     * Create an instance of {@link UniqueID }
     * 
     */
    public UniqueID createUniqueID() {
        return new UniqueID();
    }

    /**
     * Create an instance of {@link VoucherInfoListType }
     * 
     */
    public VoucherInfoListType createVoucherInfoListType() {
        return new VoucherInfoListType();
    }

    /**
     * Create an instance of {@link Membership }
     * 
     */
    public Membership createMembership() {
        return new Membership();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link RegisterKeyList }
     * 
     */
    public RegisterKeyList createRegisterKeyList() {
        return new RegisterKeyList();
    }

    /**
     * Create an instance of {@link BriefProfileList }
     * 
     */
    public BriefProfileList createBriefProfileList() {
        return new BriefProfileList();
    }

    /**
     * Create an instance of {@link Overtime }
     * 
     */
    public Overtime createOvertime() {
        return new Overtime();
    }

    /**
     * Create an instance of {@link FetchProfileResponse }
     * 
     */
    public FetchProfileResponse createFetchProfileResponse() {
        return new FetchProfileResponse();
    }

    /**
     * Create an instance of {@link MergeRequest }
     * 
     */
    public MergeRequest createMergeRequest() {
        return new MergeRequest();
    }

    /**
     * Create an instance of {@link BriefProfile }
     * 
     */
    public BriefProfile createBriefProfile() {
        return new BriefProfile();
    }

    /**
     * Create an instance of {@link NameMembershipList }
     * 
     */
    public NameMembershipList createNameMembershipList() {
        return new NameMembershipList();
    }

    /**
     * Create an instance of {@link CreditCard }
     * 
     */
    public CreditCard createCreditCard() {
        return new CreditCard();
    }

    /**
     * Create an instance of {@link AddKeyRequest }
     * 
     */
    public AddKeyRequest createAddKeyRequest() {
        return new AddKeyRequest();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link ClientImportResponse }
     * 
     */
    public ClientImportResponse createClientImportResponse() {
        return new ClientImportResponse();
    }

    /**
     * Create an instance of {@link TaxListType }
     * 
     */
    public TaxListType createTaxListType() {
        return new TaxListType();
    }

    /**
     * Create an instance of {@link LockerRequest }
     * 
     */
    public LockerRequest createLockerRequest() {
        return new LockerRequest();
    }

    /**
     * Create an instance of {@link SubscriptionResponse }
     * 
     */
    public SubscriptionResponse createSubscriptionResponse() {
        return new SubscriptionResponse();
    }

    /**
     * Create an instance of {@link TextList }
     * 
     */
    public TextList createTextList() {
        return new TextList();
    }

    /**
     * Create an instance of {@link PaymentOptionsType }
     * 
     */
    public PaymentOptionsType createPaymentOptionsType() {
        return new PaymentOptionsType();
    }

    /**
     * Create an instance of {@link ProfileLookupRequest }
     * 
     */
    public ProfileLookupRequest createProfileLookupRequest() {
        return new ProfileLookupRequest();
    }

    /**
     * Create an instance of {@link PostPaymentRequest }
     * 
     */
    public PostPaymentRequest createPostPaymentRequest() {
        return new PostPaymentRequest();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link NameCreditCard }
     * 
     */
    public NameCreditCard createNameCreditCard() {
        return new NameCreditCard();
    }

    /**
     * Create an instance of {@link QuickCheckOutRequest }
     * 
     */
    public QuickCheckOutRequest createQuickCheckOutRequest() {
        return new QuickCheckOutRequest();
    }

    /**
     * Create an instance of {@link RegisterKey }
     * 
     */
    public RegisterKey createRegisterKey() {
        return new RegisterKey();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Profile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types", name = "Profile")
    public JAXBElement<Profile> createProfile(Profile value) {
        return new JAXBElement<Profile>(_Profile_QNAME, Profile.class, null, value);
    }

}
