//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 01:38:32 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentOptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubscriptionRedeem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BonusRedeem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DiscountRedeem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DiscountRules" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BonusRules" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SubscriptionPurchase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BonusTriggers" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentOptionsType", namespace = "http://www.hrs.ru/clubng/ws/common/types", propOrder = {
    "subscriptionRedeem",
    "bonusRedeem",
    "discountRedeem",
    "discountRules",
    "bonusRules",
    "subscriptionPurchase",
    "bonusTriggers"
})
public class PaymentOptionsType {

    @XmlElement(name = "SubscriptionRedeem", namespace = "http://www.hrs.ru/clubng/ws/common/types", required = true, defaultValue = "F")
    protected String subscriptionRedeem;
    @XmlElement(name = "BonusRedeem", namespace = "http://www.hrs.ru/clubng/ws/common/types", required = true, defaultValue = "F")
    protected String bonusRedeem;
    @XmlElement(name = "DiscountRedeem", namespace = "http://www.hrs.ru/clubng/ws/common/types", required = true, defaultValue = "F")
    protected String discountRedeem;
    @XmlElement(name = "DiscountRules", namespace = "http://www.hrs.ru/clubng/ws/common/types", required = true, defaultValue = "T")
    protected String discountRules;
    @XmlElement(name = "BonusRules", namespace = "http://www.hrs.ru/clubng/ws/common/types", required = true, defaultValue = "T")
    protected String bonusRules;
    @XmlElement(name = "SubscriptionPurchase", namespace = "http://www.hrs.ru/clubng/ws/common/types", required = true, defaultValue = "F")
    protected String subscriptionPurchase;
    @XmlElement(name = "BonusTriggers", namespace = "http://www.hrs.ru/clubng/ws/common/types", required = true, defaultValue = "T")
    protected String bonusTriggers;

    /**
     * Gets the value of the subscriptionRedeem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionRedeem() {
        return subscriptionRedeem;
    }

    /**
     * Sets the value of the subscriptionRedeem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionRedeem(String value) {
        this.subscriptionRedeem = value;
    }

    /**
     * Gets the value of the bonusRedeem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBonusRedeem() {
        return bonusRedeem;
    }

    /**
     * Sets the value of the bonusRedeem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBonusRedeem(String value) {
        this.bonusRedeem = value;
    }

    /**
     * Gets the value of the discountRedeem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountRedeem() {
        return discountRedeem;
    }

    /**
     * Sets the value of the discountRedeem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountRedeem(String value) {
        this.discountRedeem = value;
    }

    /**
     * Gets the value of the discountRules property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountRules() {
        return discountRules;
    }

    /**
     * Sets the value of the discountRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountRules(String value) {
        this.discountRules = value;
    }

    /**
     * Gets the value of the bonusRules property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBonusRules() {
        return bonusRules;
    }

    /**
     * Sets the value of the bonusRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBonusRules(String value) {
        this.bonusRules = value;
    }

    /**
     * Gets the value of the subscriptionPurchase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionPurchase() {
        return subscriptionPurchase;
    }

    /**
     * Sets the value of the subscriptionPurchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionPurchase(String value) {
        this.subscriptionPurchase = value;
    }

    /**
     * Gets the value of the bonusTriggers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBonusTriggers() {
        return bonusTriggers;
    }

    /**
     * Sets the value of the bonusTriggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBonusTriggers(String value) {
        this.bonusTriggers = value;
    }

}
