//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.11 at 04:49:31 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Phone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Phone">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PhoneData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CountryAccessCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AreaCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Extension" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="phoneRole" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="phoneType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Phone", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types", propOrder = {
    "phoneNumber",
    "phoneData"
})
public class Phone {

    @XmlElement(name = "PhoneNumber", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types")
    protected String phoneNumber;
    @XmlElement(name = "PhoneData", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types")
    protected Phone.PhoneData phoneData;
    @XmlAttribute
    protected String phoneRole;
    @XmlAttribute
    protected String phoneType;

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the phoneData property.
     * 
     * @return
     *     possible object is
     *     {@link Phone.PhoneData }
     *     
     */
    public Phone.PhoneData getPhoneData() {
        return phoneData;
    }

    /**
     * Sets the value of the phoneData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Phone.PhoneData }
     *     
     */
    public void setPhoneData(Phone.PhoneData value) {
        this.phoneData = value;
    }

    /**
     * Gets the value of the phoneRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneRole() {
        return phoneRole;
    }

    /**
     * Sets the value of the phoneRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneRole(String value) {
        this.phoneRole = value;
    }

    /**
     * Gets the value of the phoneType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * Sets the value of the phoneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneType(String value) {
        this.phoneType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CountryAccessCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AreaCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Extension" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "countryAccessCode",
        "areaCode",
        "phoneNumber",
        "extension"
    })
    public static class PhoneData {

        @XmlElement(name = "CountryAccessCode", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types", required = true)
        protected String countryAccessCode;
        @XmlElement(name = "AreaCode", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types", required = true)
        protected String areaCode;
        @XmlElement(name = "PhoneNumber", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types", required = true)
        protected String phoneNumber;
        @XmlElement(name = "Extension", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types", required = true)
        protected String extension;

        /**
         * Gets the value of the countryAccessCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryAccessCode() {
            return countryAccessCode;
        }

        /**
         * Sets the value of the countryAccessCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryAccessCode(String value) {
            this.countryAccessCode = value;
        }

        /**
         * Gets the value of the areaCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAreaCode() {
            return areaCode;
        }

        /**
         * Sets the value of the areaCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAreaCode(String value) {
            this.areaCode = value;
        }

        /**
         * Gets the value of the phoneNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhoneNumber() {
            return phoneNumber;
        }

        /**
         * Sets the value of the phoneNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhoneNumber(String value) {
            this.phoneNumber = value;
        }

        /**
         * Gets the value of the extension property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtension() {
            return extension;
        }

        /**
         * Sets the value of the extension property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtension(String value) {
            this.extension = value;
        }

    }

}
