//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 01:38:32 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Profile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Profile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IDs" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types}UniqueIDList" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="Customer" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}Customer"/>
 *           &lt;element name="Company" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}Company"/>
 *         &lt;/choice>
 *         &lt;element name="CreditCards" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}NameCreditCardList" minOccurs="0"/>
 *         &lt;element name="Addresses" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}NameAddressList" minOccurs="0"/>
 *         &lt;element name="Blacklist" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}BlackList" minOccurs="0"/>
 *         &lt;element name="Phones" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}NamePhoneList" minOccurs="0"/>
 *         &lt;element name="Preferences" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}PreferenceList" minOccurs="0"/>
 *         &lt;element name="Memberships" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}NameMembershipList" minOccurs="0"/>
 *         &lt;element name="NegotiatedRates" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}NegotiatedRateList" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}CommentList" minOccurs="0"/>
 *         &lt;element name="UserDefinedValues" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types}UserDefinedValueList" minOccurs="0"/>
 *         &lt;element name="PrivacyList" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types}PrivacyList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types}RecordAdministratorAttributes"/>
 *       &lt;attribute name="languageCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nameType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nationality" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="protected" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="taxExempt" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="vipCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Profile", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types", propOrder = {
    "iDs",
    "customer",
    "company",
    "creditCards",
    "addresses",
    "blacklist",
    "phones",
    "preferences",
    "memberships",
    "negotiatedRates",
    "comments",
    "userDefinedValues",
    "privacyList"
})
public class Profile {

    @XmlElement(name = "IDs", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected UniqueIDList iDs;
    @XmlElement(name = "Customer", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected Customer customer;
    @XmlElement(name = "Company", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected Company company;
    @XmlElement(name = "CreditCards", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected NameCreditCardList creditCards;
    @XmlElement(name = "Addresses", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected NameAddressList addresses;
    @XmlElement(name = "Blacklist", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected BlackList blacklist;
    @XmlElement(name = "Phones", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected NamePhoneList phones;
    @XmlElement(name = "Preferences", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected PreferenceList preferences;
    @XmlElement(name = "Memberships", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected NameMembershipList memberships;
    @XmlElement(name = "NegotiatedRates", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected NegotiatedRateList negotiatedRates;
    @XmlElement(name = "Comments", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected CommentList comments;
    @XmlElement(name = "UserDefinedValues", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected UserDefinedValueList userDefinedValues;
    @XmlElement(name = "PrivacyList", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types")
    protected PrivacyList privacyList;
    @XmlAttribute
    protected String languageCode;
    @XmlAttribute
    protected String nameType;
    @XmlAttribute
    protected String nationality;
    @XmlAttribute(name = "protected")
    protected Boolean _protected;
    @XmlAttribute
    protected Boolean taxExempt;
    @XmlAttribute
    protected String vipCode;
    @XmlAttribute
    protected XMLGregorianCalendar inactiveDate;
    @XmlAttribute
    protected XMLGregorianCalendar insertDate;
    @XmlAttribute
    protected String insertUser;
    @XmlAttribute
    protected XMLGregorianCalendar updateDate;
    @XmlAttribute
    protected String updateUser;

    /**
     * Gets the value of the iDs property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueIDList }
     *     
     */
    public UniqueIDList getIDs() {
        return iDs;
    }

    /**
     * Sets the value of the iDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueIDList }
     *     
     */
    public void setIDs(UniqueIDList value) {
        this.iDs = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link Customer }
     *     
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Customer }
     *     
     */
    public void setCustomer(Customer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setCompany(Company value) {
        this.company = value;
    }

    /**
     * Gets the value of the creditCards property.
     * 
     * @return
     *     possible object is
     *     {@link NameCreditCardList }
     *     
     */
    public NameCreditCardList getCreditCards() {
        return creditCards;
    }

    /**
     * Sets the value of the creditCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCreditCardList }
     *     
     */
    public void setCreditCards(NameCreditCardList value) {
        this.creditCards = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link NameAddressList }
     *     
     */
    public NameAddressList getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameAddressList }
     *     
     */
    public void setAddresses(NameAddressList value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the blacklist property.
     * 
     * @return
     *     possible object is
     *     {@link BlackList }
     *     
     */
    public BlackList getBlacklist() {
        return blacklist;
    }

    /**
     * Sets the value of the blacklist property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlackList }
     *     
     */
    public void setBlacklist(BlackList value) {
        this.blacklist = value;
    }

    /**
     * Gets the value of the phones property.
     * 
     * @return
     *     possible object is
     *     {@link NamePhoneList }
     *     
     */
    public NamePhoneList getPhones() {
        return phones;
    }

    /**
     * Sets the value of the phones property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamePhoneList }
     *     
     */
    public void setPhones(NamePhoneList value) {
        this.phones = value;
    }

    /**
     * Gets the value of the preferences property.
     * 
     * @return
     *     possible object is
     *     {@link PreferenceList }
     *     
     */
    public PreferenceList getPreferences() {
        return preferences;
    }

    /**
     * Sets the value of the preferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreferenceList }
     *     
     */
    public void setPreferences(PreferenceList value) {
        this.preferences = value;
    }

    /**
     * Gets the value of the memberships property.
     * 
     * @return
     *     possible object is
     *     {@link NameMembershipList }
     *     
     */
    public NameMembershipList getMemberships() {
        return memberships;
    }

    /**
     * Sets the value of the memberships property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameMembershipList }
     *     
     */
    public void setMemberships(NameMembershipList value) {
        this.memberships = value;
    }

    /**
     * Gets the value of the negotiatedRates property.
     * 
     * @return
     *     possible object is
     *     {@link NegotiatedRateList }
     *     
     */
    public NegotiatedRateList getNegotiatedRates() {
        return negotiatedRates;
    }

    /**
     * Sets the value of the negotiatedRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link NegotiatedRateList }
     *     
     */
    public void setNegotiatedRates(NegotiatedRateList value) {
        this.negotiatedRates = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link CommentList }
     *     
     */
    public CommentList getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentList }
     *     
     */
    public void setComments(CommentList value) {
        this.comments = value;
    }

    /**
     * Gets the value of the userDefinedValues property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedValueList }
     *     
     */
    public UserDefinedValueList getUserDefinedValues() {
        return userDefinedValues;
    }

    /**
     * Sets the value of the userDefinedValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedValueList }
     *     
     */
    public void setUserDefinedValues(UserDefinedValueList value) {
        this.userDefinedValues = value;
    }

    /**
     * Gets the value of the privacyList property.
     * 
     * @return
     *     possible object is
     *     {@link PrivacyList }
     *     
     */
    public PrivacyList getPrivacyList() {
        return privacyList;
    }

    /**
     * Sets the value of the privacyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivacyList }
     *     
     */
    public void setPrivacyList(PrivacyList value) {
        this.privacyList = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the nameType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameType() {
        return nameType;
    }

    /**
     * Sets the value of the nameType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameType(String value) {
        this.nameType = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the protected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProtected() {
        return _protected;
    }

    /**
     * Sets the value of the protected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProtected(Boolean value) {
        this._protected = value;
    }

    /**
     * Gets the value of the taxExempt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxExempt() {
        return taxExempt;
    }

    /**
     * Sets the value of the taxExempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxExempt(Boolean value) {
        this.taxExempt = value;
    }

    /**
     * Gets the value of the vipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVipCode() {
        return vipCode;
    }

    /**
     * Sets the value of the vipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVipCode(String value) {
        this.vipCode = value;
    }

    /**
     * Gets the value of the inactiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInactiveDate() {
        return inactiveDate;
    }

    /**
     * Sets the value of the inactiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInactiveDate(XMLGregorianCalendar value) {
        this.inactiveDate = value;
    }

    /**
     * Gets the value of the insertDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInsertDate() {
        return insertDate;
    }

    /**
     * Sets the value of the insertDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInsertDate(XMLGregorianCalendar value) {
        this.insertDate = value;
    }

    /**
     * Gets the value of the insertUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsertUser() {
        return insertUser;
    }

    /**
     * Sets the value of the insertUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsertUser(String value) {
        this.insertUser = value;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateDate(XMLGregorianCalendar value) {
        this.updateDate = value;
    }

    /**
     * Gets the value of the updateUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * Sets the value of the updateUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateUser(String value) {
        this.updateUser = value;
    }

}
