//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 01:38:32 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="briefProfileList" type="{http://www.hrs.ru/clubng/ws/common/types}BriefProfileList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "briefProfileList"
})
@XmlRootElement(name = "ProfileLookupResponse")
public class ProfileLookupResponse {

    @XmlElement(required = true)
    protected BriefProfileList briefProfileList;

    /**
     * Gets the value of the briefProfileList property.
     * 
     * @return
     *     possible object is
     *     {@link BriefProfileList }
     *     
     */
    public BriefProfileList getBriefProfileList() {
        return briefProfileList;
    }

    /**
     * Sets the value of the briefProfileList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BriefProfileList }
     *     
     */
    public void setBriefProfileList(BriefProfileList value) {
        this.briefProfileList = value;
    }

}
