//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.28 at 01:38:32 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PostingGUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PostPropertyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RevenueCenterId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VoidFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CheckNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChkTtl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CashierEmpName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Voucher" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "postingGUID",
    "postPropertyId",
    "revenueCenterId",
    "voidFlag",
    "checkNumber",
    "chkTtl",
    "cashierEmpName",
    "voucher"
})
@XmlRootElement(name = "RedeemItemVoucherRequest")
public class RedeemItemVoucherRequest {

    @XmlElement(name = "PostingGUID")
    protected String postingGUID;
    @XmlElement(name = "PostPropertyId", required = true)
    protected String postPropertyId;
    @XmlElement(name = "RevenueCenterId", required = true)
    protected String revenueCenterId;
    @XmlElement(name = "VoidFlag")
    protected Boolean voidFlag;
    @XmlElement(name = "CheckNumber", required = true)
    protected String checkNumber;
    @XmlElement(name = "ChkTtl", required = true)
    protected String chkTtl;
    @XmlElement(name = "CashierEmpName")
    protected String cashierEmpName;
    @XmlElement(name = "Voucher", required = true)
    protected String voucher;

    /**
     * Gets the value of the postingGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostingGUID() {
        return postingGUID;
    }

    /**
     * Sets the value of the postingGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostingGUID(String value) {
        this.postingGUID = value;
    }

    /**
     * Gets the value of the postPropertyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostPropertyId() {
        return postPropertyId;
    }

    /**
     * Sets the value of the postPropertyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostPropertyId(String value) {
        this.postPropertyId = value;
    }

    /**
     * Gets the value of the revenueCenterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueCenterId() {
        return revenueCenterId;
    }

    /**
     * Sets the value of the revenueCenterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueCenterId(String value) {
        this.revenueCenterId = value;
    }

    /**
     * Gets the value of the voidFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVoidFlag() {
        return voidFlag;
    }

    /**
     * Sets the value of the voidFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVoidFlag(Boolean value) {
        this.voidFlag = value;
    }

    /**
     * Gets the value of the checkNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckNumber() {
        return checkNumber;
    }

    /**
     * Sets the value of the checkNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckNumber(String value) {
        this.checkNumber = value;
    }

    /**
     * Gets the value of the chkTtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChkTtl() {
        return chkTtl;
    }

    /**
     * Sets the value of the chkTtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChkTtl(String value) {
        this.chkTtl = value;
    }

    /**
     * Gets the value of the cashierEmpName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashierEmpName() {
        return cashierEmpName;
    }

    /**
     * Sets the value of the cashierEmpName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashierEmpName(String value) {
        this.cashierEmpName = value;
    }

    /**
     * Gets the value of the voucher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucher() {
        return voucher;
    }

    /**
     * Sets the value of the voucher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucher(String value) {
        this.voucher = value;
    }

}
