//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.11 at 04:49:31 PM YEKT 
//


package ru.hrs.lassd.club.ws.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Subscription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Subscription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProfileIDs" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types}UniqueIDList"/>
 *       &lt;/sequence>
 *       &lt;attribute name="otherSubscriptionAction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subscriptionAction" use="required" type="{http://htng.org/PWS/2008A/SingleGuestItinerary/Common/Types}SubscriptionAction" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Subscription", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types", propOrder = {
    "profileIDs"
})
public class Subscription {

    @XmlElement(name = "ProfileIDs", namespace = "http://htng.org/PWS/2008A/SingleGuestItinerary/Name/Types", required = true)
    protected UniqueIDList profileIDs;
    @XmlAttribute
    protected String otherSubscriptionAction;
    @XmlAttribute(required = true)
    protected SubscriptionAction subscriptionAction;

    /**
     * Gets the value of the profileIDs property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueIDList }
     *     
     */
    public UniqueIDList getProfileIDs() {
        return profileIDs;
    }

    /**
     * Sets the value of the profileIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueIDList }
     *     
     */
    public void setProfileIDs(UniqueIDList value) {
        this.profileIDs = value;
    }

    /**
     * Gets the value of the otherSubscriptionAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherSubscriptionAction() {
        return otherSubscriptionAction;
    }

    /**
     * Sets the value of the otherSubscriptionAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherSubscriptionAction(String value) {
        this.otherSubscriptionAction = value;
    }

    /**
     * Gets the value of the subscriptionAction property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionAction }
     *     
     */
    public SubscriptionAction getSubscriptionAction() {
        return subscriptionAction;
    }

    /**
     * Sets the value of the subscriptionAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionAction }
     *     
     */
    public void setSubscriptionAction(SubscriptionAction value) {
        this.subscriptionAction = value;
    }

}
